package org.rsm.finjournal.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-11-24T12:13:11.940-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "org:rsm:finjournal:service", name = "FinjournalService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FinjournalService {

    @WebResult(name = "FinancialSummaryResponse", targetNamespace = "org:rsm:finjournal:service", partName = "FinancialSummaryResponse")
    @WebMethod(operationName = "GetFinancialSummary", action = "org:rsm:finjournal:service/GetFinancialSummary")
    public FinancialSummaryResponse getFinancialSummary(
        @WebParam(partName = "FinancialSummaryRequest", name = "FinancialSummaryRequest", targetNamespace = "org:rsm:finjournal:service")
        FinancialSummaryRequest financialSummaryRequest
    );
}
